server:
  port: 9101
  max-http-header-size: 756000
  jetty:
    threads:
      min: 100
      max: 3000
      idle-timeout: 10000
    connection-idle-timeout: 10000
    accesslog:
      enabled: true
  servlet:
    encoding:
      force: true
      charset: UTF-8

service:
  api:
    base-path: /services/${spring.application.name}
  swagger:
    title: 'sample service client'
    description: 'sample service client service'
    version: 'version1.0.0-1401/06/14 10:40'

  provider:
    name: sample-service-provider
    baseUrl: http://${service.provider.name}
    users: /services/${service.provider.name}/goRest/users
    posts: /services/${service.provider.name}/goRest/posts
    findUserById: /services/${service.provider.name}/goRest/findUserById
    findPostById: /services/${service.provider.name}/goRest/findPostById
  restTemplate:
    connectionPerRoute: 300
    maxTotalConnection: 3000
    connectionTimeout: 10000
    socketTimeout: 30000
    connectionRequestTimeout: 30000
    connectionTimeToLive: 30000



spring:
  application:
    name: sample-service-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}


camel:
  springboot:
    main-run-controller: true
    jmx-management-statistics-level: extended
    endpoint-runtime-statistics-enabled: true
    jmx-enabled: true
  cloud:
    consul:
      service-host: localhost
      url: http://localhost:8500
      id: ${spring.application.name}
      registrationScheduled: 30000
    service-call:
      default-load-balancer: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    display-operation-id: true
  api-docs:
    path: /${spring.application.name}/v3/api-docs


management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /actuators/${spring.application.name}
      exposure:
        include: '*'
